language: cpp
sudo: false

branches:
  only:
    - master

cache: apt

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

matrix:
  include:
  - os: linux
    compiler: g++-5

script:
  - make